#!/bin/sh

CATEGORIZE_FILE="/home/sandy/.arbtt/categorize.cfg"
CATEGORY="prj"
FILTER="\$sampleage <= 2922:00" # Last 4 months

arbtt-stats --for-each=day \
              --output-format=CSV \
              --min-percentage=1.5 \
              --filter="$FILTER" \
              > /tmp/daily.csv

arbtt-stats --for-each=minute \
              --output-format=CSV \
              --min-percentage=1.5 \
              --filter="$FILTER" \
              > /tmp/minute.csv

python3 readArbttStats.py -c 'misc' -d /tmp/daily.csv -m /tmp/minute.csv
